site_name: Sune Beermann
site_url: https://runnerz.org/
repo_url: https://github.com/beermann/runnerz
repo_name: beermann/runnerz
edit_uri: edit/main/docs

nav:
  - News: blog/index.md
  - About: about.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: Roboto Mono
  language: en
  features:
    - content.action.edit
    - content.core.copy
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: gray
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - blog:
      #authors_file: .authors.yml
      authors: true
  - social:
      #cards_layout: default
  - search:

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: 0

copyright: 2023 - 2024 &copy; Sune Beermann - This work is licensed under CC BY-NC-SA 4.0
extra_javascript:

  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra:
  social:
      - icon: 'fontawesome/brands/github'
        link: 'https://github.com/beermann'
        name: Beermann on GitHub
      - icon: 'fontawesome/brands/linkedin'
        link: 'https://dk.linkedin.com/in/sunebeermann'
        name: Sune Beermann
      - icon: 'fontawesome/regular/square-check'
        link: 'https://forum.checkmk.com/'
        name: Beermann

 #consent:
 #  title: Cookie consent
 #  description: >- 
 #    We use cookies to recognize your repeated visits and preferences, as well
 #    as to measure the effectiveness of our documentation and whether users
 #    find what they're searching for. With your consent, you're helping us to
 #    make our documentation better.
